#include <cstring>
#include <errno.h>

#include "error_code.h"

namespace comno
{
#define __error_code_name__(errno) case errno: return #errno;

const char* error_code::to_string() const
{
    switch(_errno){
        __error_code_name__(EPERM)
        __error_code_name__(ENOENT)
        __error_code_name__(ESRCH)
        __error_code_name__(EINTR)
        __error_code_name__(EIO)
        __error_code_name__(ENXIO)
        __error_code_name__(E2BIG)
        __error_code_name__(ENOEXEC)
        __error_code_name__(EBADF)
        __error_code_name__(ECHILD)
        __error_code_name__(EAGAIN)
        //__error_code_name__(EWOULDBLOCK)
        __error_code_name__(ENOMEM)
        __error_code_name__(EACCES)
        __error_code_name__(EFAULT)
        __error_code_name__(ENOTBLK)
        __error_code_name__(EBUSY)
        __error_code_name__(EEXIST)
        __error_code_name__(EXDEV)
        __error_code_name__(ENODEV)
        __error_code_name__(ENOTDIR)
        __error_code_name__(EISDIR)
        __error_code_name__(EINVAL)
        __error_code_name__(ENFILE)
        __error_code_name__(EMFILE)
        __error_code_name__(ENOTTY)
        __error_code_name__(ETXTBSY)
        __error_code_name__(EFBIG)
        __error_code_name__(ENOSPC)
        __error_code_name__(ESPIPE)
        __error_code_name__(EROFS)
        __error_code_name__(EMLINK)
        __error_code_name__(EPIPE)
        __error_code_name__(EDOM)
        __error_code_name__(ERANGE)
        __error_code_name__(EDEADLK)
        //__error_code_name__(EDEADLOCK)
        __error_code_name__(ENAMETOOLONG)
        __error_code_name__(ENOLCK)
        __error_code_name__(ENOSYS)
        __error_code_name__(ENOTEMPTY)
        __error_code_name__(ELOOP)
        __error_code_name__(ENOMSG)
        __error_code_name__(EIDRM)
        __error_code_name__(ECHRNG)
        __error_code_name__(EL2NSYNC)
        __error_code_name__(EL3HLT)
        __error_code_name__(EL3RST)
        __error_code_name__(ELNRNG)
        __error_code_name__(EUNATCH)
        __error_code_name__(ENOCSI)
        __error_code_name__(EL2HLT)
        __error_code_name__(EBADE)
        __error_code_name__(EBADR)
        __error_code_name__(EXFULL)
        __error_code_name__(ENOANO)
        __error_code_name__(EBADRQC)
        __error_code_name__(EBADSLT)
        __error_code_name__(EBFONT)
        __error_code_name__(ENOSTR)
        __error_code_name__(ENODATA)
        __error_code_name__(ETIME)
        __error_code_name__(ENOSR)
        __error_code_name__(ENONET)
        __error_code_name__(ENOPKG)
        __error_code_name__(EREMOTE)
        __error_code_name__(ENOLINK)
        __error_code_name__(EADV)
        __error_code_name__(ESRMNT)
        __error_code_name__(ECOMM)
        __error_code_name__(EPROTO)
        __error_code_name__(EMULTIHOP)
        __error_code_name__(EDOTDOT)
        __error_code_name__(EBADMSG)
        __error_code_name__(EOVERFLOW)
        __error_code_name__(ENOTUNIQ)
        __error_code_name__(EBADFD)
        __error_code_name__(EREMCHG)
        __error_code_name__(ELIBACC)
        __error_code_name__(ELIBBAD)
        __error_code_name__(ELIBSCN)
        __error_code_name__(ELIBMAX)
        __error_code_name__(ELIBEXEC)
        __error_code_name__(EILSEQ)
        __error_code_name__(ERESTART)
        __error_code_name__(ESTRPIPE)
        __error_code_name__(EUSERS)
        __error_code_name__(ENOTSOCK)
        __error_code_name__(EDESTADDRREQ)
        __error_code_name__(EMSGSIZE)
        __error_code_name__(EPROTOTYPE)
        __error_code_name__(ENOPROTOOPT)
        __error_code_name__(EPROTONOSUPPORT)
        __error_code_name__(ESOCKTNOSUPPORT)
        __error_code_name__(EOPNOTSUPP)
        __error_code_name__(EPFNOSUPPORT)
        __error_code_name__(EAFNOSUPPORT)
        __error_code_name__(EADDRINUSE)
        __error_code_name__(EADDRNOTAVAIL)
        __error_code_name__(ENETDOWN)
        __error_code_name__(ENETUNREACH)
        __error_code_name__(ENETRESET)
        __error_code_name__(ECONNABORTED)
        __error_code_name__(ECONNRESET)
        __error_code_name__(ENOBUFS)
        __error_code_name__(EISCONN)
        __error_code_name__(ENOTCONN)
        __error_code_name__(ESHUTDOWN)
        __error_code_name__(ETOOMANYREFS)
        __error_code_name__(ETIMEDOUT)
        __error_code_name__(ECONNREFUSED)
        __error_code_name__(EHOSTDOWN)
        __error_code_name__(EHOSTUNREACH)
        __error_code_name__(EALREADY)
        __error_code_name__(EINPROGRESS)
        __error_code_name__(ESTALE)
        __error_code_name__(EUCLEAN)
        __error_code_name__(ENOTNAM)
        __error_code_name__(ENAVAIL)
        __error_code_name__(EISNAM)
        __error_code_name__(EREMOTEIO)
        __error_code_name__(EDQUOT)
        __error_code_name__(ENOMEDIUM)
        __error_code_name__(EMEDIUMTYPE)
        __error_code_name__(ECANCELED)
        __error_code_name__(ENOKEY)
        __error_code_name__(EKEYEXPIRED)
        __error_code_name__(EKEYREVOKED)
        __error_code_name__(EKEYREJECTED)
        __error_code_name__(EOWNERDEAD)
        __error_code_name__(ENOTRECOVERABLE)
        __error_code_name__(ERFKILL)
        __error_code_name__(EHWPOISON)
        default: return "unknown";
    }

    return "unknown";
}

const char* error_code::details() const
{
    return ::strerror(_errno);
}
}
